### PR TITLE
feat(ios): add ios12 notification providesAppNotificationSettings

### PR DESCRIPTION
**Pull request by francois-pasquier**
Closes https://github.com/nativescript-community/perms/issues/7

### CODE REVIEW

**Comment by farfromrefug** [comment]
@francois-pasquier merci bcp pour ta PR! je te fais une release au plus vite! (tu es bien Francais il me semble ;))

**Comment by francois-pasquier** [comment]
> @francois-pasquier merci bcp pour ta PR! je te fais une release au plus vite! (tu es bien Francais il me semble ;))

Top, merci beaucoup : )

**Comment by farfromrefug** [comment]
@francois-pasquier did you test it ? `UIUserNotificationType.ProvidesAppNotificationSetting` does not seem to exist. should'nt we use `UNNotificationSettings.providesAppNotificationSettings`?

**Comment by farfromrefug** [comment]
@francois-pasquier no i ll fix it. Looking at https://github.com/mrousavy/react-native-notification-badge now to see how they do it

**Comment by francois-pasquier** [comment]
Sorry for the trouble!

**Comment by farfromrefug** [comment]
@francois-pasquier could you try this and report if it works on iOS >= 12 ?
[nativescript-community-perms-2.1.8.zip](https://github.com/nativescript-community/perms/files/7278527/nativescript-community-perms-2.1.8.zip)

**Pull request merged**
